### PR TITLE
GH-25: Fix registering wrong source set

### PR DESCRIPTION
**Pull request by lukasz-kaminski**
Resolves GH-25

### CODE REVIEW

**Comment by lukasz-kaminski** [comment]
Since I can't add reviewers I'll summon @king-tyler :)

**Comment by king-tyler** [comment]
Xtext generates a `.xtextbin` file into the runtime project's srcGen folder. This file needs to be included in the jar for eclipse to properly load the plugin and parse the dsl, which is why the srcGen folder is included in Gradle's resources directory. I'll look into copying that file from srcGen to the generated resource directory instead.

**Comment by lukasz-kaminski** [comment]
Thanks for the info @king-tyler!

**Comment by king-tyler** [comment]
Fixed in #31

**Pull request closed without merging**
